GeoNet/delta

- tests/marks_test.go
- tests/stations_test.go
Start and end properties in the GeoJSON as RFC3339 (instead of epoch).  This makes them the same as other timestamps in GeoJSON from api.geonet.org.nz for consistency.
> RFC3339 timestamps in GeoJSON.

- tools/pod/blockette.go
- tools/pod/pod.go
@quiffman stationxml prefers lowercase unit names whereas the traditional dataless seed liked uppercase. 
I've also allowed unknown sensors to be added to the abbreviation list, the matching cases are there to allow comparison with the existing files for checking/testing (missing ones will not match any so should be fine to add as is).
> updated pod abbreviations to handle stationxml style units

- tools/pod/pod.go
@quiffman Small bug shown up in comparing stationxml derived dataless volumes vs the current set. It comes out with the wrong network abbreviation code for non-national network sites (i.e. they should all be "New Zealand ...." but some were coming out like "Tongariro Network ..."
> update pod to use network description rather than station description

- build.sh
- tools/stationxml/build.go
- tools/stationxml/main.go
@quiffman starting to look at tailoring the stationxml extracts, a couple of constraints from the old system were missing, these were being specific about loggers and sensors to be extracted. I've also added for real-time related work whether the site is currently, or recently, operational.
e.g. this is the original mapping for the IRIS dataless SEED files.
```
$pod->streams(
network_remap => {'CH' => 'NZ'},
networks => ['NZ', 'CH'],
stations => ['KHZ', 'QRZ', 'OUZ', 'HIZ', 'BKZ', 'ODZ', 'BFZ', 'CTZ', 'URZ', 'RPZ', 'WPVZ'],
sensors => ['STS-2', 'CMG-3TB', 'CMG-40T-60S', 'FBA-ES-T'],
loggers => ['Q330HR/6', 'Q4120/6', 'Q330/3'],
channels => ['HHZ', 'HHN', 'HHE', 'HH1', 'HH2', 'LHZ', 'LHN', 'LHE', 'LH1', 'LH2', 'VHZ', 'VHN', 'VHE', 'VH1', 'VH2', 'HNZ', 'HNN', 'HNE', 'BNZ', 'BNN', 'BNE', …
```
> added extra stationxml constraints for logger/sensor and operational state

- build.sh
@quiffman turns out the aws sync of the pod directories (large number of small files) was taking too long for travis and may not have been a good idea in any case.
I've made the build script now generate compressed tar files which should avoid the problem. This will also make checking for changes much easier for the downstream processors as well.
> rework build script to generate pod tar files

- resp/auto.go
- resp/responses/dataloggers.yaml
- resp/responses/responses.yaml
- tools/impact/build.go
@quiffman  I've added the Obsidian 4x response information, it acts like a datalogger (no internal sensor) rather than the normal Obsidian (which is a recorder). The `auto.go` file is generated via `go generate` from the information stored in the `yaml` files.
I've also add the 4x to the "blessed" instrument list for the impact service which should solve GeoNet/tickets#1479
The instrument names come directly out of the oracle db and can be looked at again once this is no longer a constraint.
/cc @nbalfour @gclitheroe
> add obsidian 4x response

- build.sh
Two commits here - happy to take feedback on either or both.
I was getting a little wound up about the repetition of compilation, so I pared it out into a separate step.
Hopefully it still makes sense this way.
I also added automatic generation of `impact.json`, which will arrive in the bucket as `/config/impact.json`.
Totally ambivalent about the object naming and happy to change if required.
> Rejig the build script and add impact.json

- tests/antennas_test.go
- tests/assets_test.go
- tests/cameras_test.go
- tests/combined_test.go
- tests/connections_test.go
- tests/consistency_test.go
- tests/constituents_test.go
- tests/dataloggers_test.go
- tests/firmware_test.go
- tests/gauges_test.go
- tests/marks_test.go
- tests/metsensors_test.go
- tests/monuments_test.go
- tests/networks_test.go
- tests/radomes_test.go
- tests/receivers_test.go
- tests/recorders_test.go
- tests/sensors_test.go
- tests/sessions_test.go
- tests/sites_test.go
- tests/streams_test.go
@dc735 an update to the testing code. There's not much new here, rather a switch to using the `t.Run` mechanism that became available in `go 1.7`. 
It basically allows some form of isolation between tests (one part can have a fatal result and stop but other parts will continue to be tested if possible).
I've also tried to make them a little more readable, e.g. being explicit about lists of 
> `if ( something ) { continue }` 
rather than use a switch which is more compact but isn't as obvious what it's doing.
I've also brought all the `csv` file loading parts into a single function which is called with the test variable so that it can have a fatal error.
There are still a couple of tests that only make a warning message (need `go test -v` to see them), I'll think of a way to bring these …
> update tests to use t.Run

- .travis.yml
- tools/sit/sit_build.sh
This should hopefully fix the unintended behaviour that @quiffman noticed on Friday where the remote triggering of SIT was happening after EACH individual deploy (i.e. 3 times) rather than the expected once after all deploy steps were completed.
> Multi Trigger Fix

- resp/auto.go
- resp/responses/sensors/kinemetrics.yaml
The PAZ lookup for the borehole SBEPI sensor was set to a missing value, this should have been pointing to the existing FBA-ES-T lookup.
> updated kinemtrics sbepi paz

- tools/stationxml/build.go
- tools/stationxml/response.go
- tools/stationxml/stage.go
@danieldooley to make the latest govet happy, this will be needed before updating the go version as per #469 
Only adds "Float:" and "Time:" to the composite literals.
> fixed govet "composite literal uses unkeyed fields" warning

- tools/pod/blockette.go
- tools/pod/pod.go
> The NZ dataless since 20190107 have failed to load into our DB due to the Blockette 32 Dictionary information.
> There is not enough information provided in the “Cited_Source 0001 Unknown” provided in the Dictionary:
This is related to building the POD headers, the entry in question will have existed in the previous system and has been retained to make checking the change between systems easier (i.e. Oracle based vs git based).  The generic "unknown" abbreviation is no longer required so removing it.
> removed the unused generic unknown source abbr.

- environment/visibility.csv
Time series (particularly East and Up components) at NLSN was affected by vegetation (groes) growing around the antenna. 
Vegetation was cut on the 26th of April 2019, and position solution is now back to a value recorded in early January 2019, which I'm setting here as the start of a period where GNSS satellites visibility got worse.
https://fits.geonet.org.nz/plot?type=scatter&sites=NLSN&typeID=e&start=2018-08-01T00:00:00Z&days=300
https://fits.geonet.org.nz/plot?type=scatter&sites=NLSN&typeID=u&start=2018-08-01T00:00:00Z&days=300
> NLSN GNSS antenna cleared from vegetation

- assets/antennas.csv
The antenna installed between Dec 2010 and July 2011 at MAVL GNSS site was probably malfunctioning, with largest impact on the North component.
This is confirmed by some independent test data from October 2017, where we have used this antenna for some testing and noticed again an unexplained offset in the North component when swapping with other antennas. That antenna (TRM57971 sn. 1441027455) has not been installed elsewhere since 2011.
/cc @nbalfour @ozym
> MAVL 2011 GNSS antenna adversely impacting time series

- tools/caps/main.go
- tools/caps/station_test.go
This is a fairly simple tool to add caps style template files to a given directory.
It has a few features that may not be used yet (e.g. unmatch) as the environment that it will run in hasn't been completely defined yet.
More constraints which stations should be included can be added (or removed) once we have a better idea of what's needed in the actual caps instance.
> add caps tool

- tools/caps/main.go
- tools/sc3/main.go
Turns out it's "key", not "keys" for caps ...
> switched default caps keys directory

- test.sh
- tools/sc3/autopick.go
- tools/sc3/autopick_test.go
- tools/sc3/main.go
- tools/sc3/station.go
- tools/sc3/station_test.go
@ardrigh @salichon There is a corner case at the moment that involves a site having multiple sensors.  The output sc3 profile may use a less desired stream ..... This PR will adjust it to favour the channel set with the "lowest" location code in an alphabetical sense.
> only use the lowest matching location code

- build.sh
IRIS special metadata volumes were not accounting for BASALT
strong motion dataloggers used at some sites (QRZ)
> IRIS metadata updated (QRZBN21 fix)

- network/mounts.csv
As per delta meeting, removing the extra entry for mount `N` in the mounts.csv file
It was introduced in PR: https://github.com/GeoNet/delta/pull/530 but is not required.
> Remove superfluous mounts.csv entry for N

- run/deploy/10-ac-tools-trigger.sh
There's a problem with the ac-tools script, it works but has an error state when the return indicates a "pending" state (will eventually work). We may be able to trap on another status code.
> add little more debugging on ac-tools script

- run/deploy/10-ac-tools-trigger.sh
Hopefully the extra check for 202 will be enough for a non-errored travis run.
> **202 ACCEPTED**
> The request has been accepted for processing, but the processing has not been completed. The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place.
> update ac-tools return code

- network/monuments.csv
Hi @CBurton90 , 
I realised that for "Wyatt/Agnew Drilled-Braced" that are shallow (foundation less than 5 m), we are using a different description in the monument.csv file, which is "Shallow Rod / Braced Antenna Mount".
Both monuments have depths of ~3.2 m, so this pull request is updating our database accordingly.
Thanks!
Elisabetta
> update Fiordland GNSS sites monuments description

- network/monuments.csv
This is to update the monument of a site that was deployed at GNS premises in Gracefield (Lower Hutt).
The site has been decommissioned, but previous records I am reviewing show that this site states was monumented as a mast (assuming a steel rod one as I can't find photos).
> update monument of decommissioned GNSS site

- tests/receivers_test.go
Hi @ozym 
this pr is based on your modification to update the receiver test and don't allow anymore for GNSS receiver installation to have the same start and stop time.
Now that the delta entries have been fixed, the test passes ok.
Please just reject this pr if you already have it somewhere else
```[elidana@hutl16534 delta]$ ./test.sh 
+ errcount=0
+ trap error_handler ERR
+ go test ./meta
ok  	github.com/GeoNet/delta/meta	(cached)
+ go test ./tides
ok  	github.com/GeoNet/delta/tides	(cached)
+ go test ./tests
ok  	github.com/GeoNet/delta/tests	(cached)
+ go test ./tools/stationxml
ok  	github.com/GeoNet/delta/tools/stationxml	(cached)
+ go test ./tools/altus
ok  	github.com/GeoNet/delta/tools/altus	(cached)
+ go test ./tools/cusp
ok  	github.com/GeoNet/delta/tools/cusp	(cached)
+ go …
```
> update test on GNSS receiver timestamp

- install/dataloggers.csv
As have LRDCP dataloggers in assets/dataloggers.csv, can now add to install/dataloggers.csv
Role column intentionally blank as Mark said it's rarely used.
https://github.com/GeoNet/tickets/issues/8076
> add lrdcp CR6 https://github.com/GeoNet/tickets/issues/8076

- internal/metadb/streams.go
- resp/generate/generate.go
This gets ready to build the response information for any streams that are sampled longer than 1 Hz.
The value `-900` is actually 15m sampling ( -1/-900) seconds.  When the streams are loaded into the memory this conversion is made so that it needs to be used for comparing against pre-calculated responses.
One side benefit is that the longer the sampling interval the lower the negative number gets, so the ordering in the streams files can be maintained (i.e -600 < -15 etc.).
> handle sample rates less than 1 Hz in responses

- resp/auto.go
- resp/responses/configurations/pressure.yaml
- resp/responses/sensors/generic.yaml
To avoid one possible problem when loading the derived stationxml.
> remove spaces from dart filter names

- tools/sitelogs/config/config.yaml
- tools/sitelogs/config_auto.go
Hi, 
IGS has recommended to avoid personal contact in IGS stations sitelogs.
The IGS public sitelogs of our stations has now been updated on the Site Log Manager.
This pr is to reflect a similar change on sitelogs of all our GNSS continuous sites. 
I have tested locally the change and it works fine. This pr is also updating the repository to https://data.geonet.org.nz
> update geodetic contact to comply with IGS latest recommendations

- install/README.md
- install/calibrations.csv
- install/gains.csv
- internal/metadb/calibrations.go
- internal/metadb/gains.go
- internal/metadb/metadb.go
- meta/calibration.go
- meta/gain.go
- meta/list_test.go
- meta/testdata/calibrations.csv
- meta/testdata/gains.csv
- resp/response.go
- tests/calibrations_test.go
- tests/consistency_test.go
- tests/gains_test.go
This work is a follow on from what's required to add geomag meta data to delta, the geomag fluxgate installations have gain settings which are independent of both the sensor and the datalogger (a driver box).
By adding a gain table the complexity of the response calculation can be reduced, that is the sensor response and datalogger responses can stay constant for all installs, but individual gain adjustments can be made as required without having to track which sensor or datalogger was installed where.
The channel is defined as the expected output of the response requirement (in miniseed this would be the final channel label, e.g. ZNE, or Z12 etc), multiple values can be used if the gains or offsets impact all channels.
The calibration table is aimed at sensors where a known calibration …
> add gain and calibration tables

- environment/README.md
- environment/placenames.csv
- meta/list_test.go
- meta/placenames.go
- meta/testdata/placenames.csv
- tests/placenames_test.go
This is part of the stationxml work to bring as much ad hoc meta data into manageable tables.
This PR provides a list of place names from which sites, or otherwise, can be compared against. It uses a level system which means that small places at large distances a skipped in favour of any nearby larger localities.
This is likely to need expanding beyond the current scope.
> add placenames environment table

- delta.go
- delta_test.go
- meta/generate/generate.go
- meta/generate/main.go
- meta/set.go
- meta/set_auto.go
- meta/set_test.go
This is an initial mechanism to gather all the various csv based files together into a single structure.
This is aimed at mainly two primary use cases:
- testing 
- CI/CD
The first testing phase allows building a standard call fingerprint for running a given test, e.g.
```golang
var testInstalledAntennas = map[string]func(*meta.Set) func(t *testing.T){
"check antenna installation overlap": func(set *meta.Set) func(t *testing.T) {
return func(t *testing.T) {
```
which makes table driven testing much easier (this will be a follow up bit of work).
and for the second part with CI/CD.
The program simply needs to be compiled to have access to the current set of files, basically due to the embedding the files live within the go binary which makes writing programs to build configuration simpler …
> add delta set helper

- delta.go
This is a small helper shortcut to allow using a base directory rather than the built in embedded files.
> add delta new base func

- cmd/camera-config/README.md
- cmd/camera-config/caption.go
- cmd/camera-config/caption_test.go
- cmd/camera-config/main.go
- cmd/volcam-config/README.md
- cmd/volcam-config/main.go
- cmd/volcam-config/volcam.go
- cmd/volcam-config/volcam_test.go
This PR adds two config tools for camera images.
The first is used simply to caption an image if needed, it uses the mounts and views tables.
The second is related to volcams, so adds in some extra detail regarding actual volcano targets.
> add volcano camera config tools

- references/README.md
- references/citations.csv
The work on polarities has indicated that there will be a need for some mechanism for citing references or other associated external information.
To this end, I've made an example "citations.csv" formatted table. I've placed it under the `references` folder for want of anything else.  I haven't used the word "reference" in the names as this clashes with the use of this term for defining where something is, i.e. with reference to this point.
I've also started looking at adding a DOI mechanism. This may be expanded as needed or appropriate to other tables. especially the network table.
This mechanism should also be able to present "web" type links so, other than the key, all fields should be optional.
I haven't defined a "key" style, but the constraints are that it be unique, and the table …
> add citations poc

- meta/doi.go
- meta/doi_test.go
This PR adds a small function which can validate DOI entries, it is currently intended for the references tables, but could also be used if DOI values are added into the main tables at some point.
> add doi decoding code

- install/README.md
- meta/channel.go
- meta/component.go
- meta/list_test.go
- meta/testdata/channels.csv
- meta/testdata/components.csv
This attempts to add a reference mechanism to link simple responses (given by a label) to a sensor component (and also include base characteristics like dip and azimuth), or to a datalogger channel using a pin offset and a sampling rate. The edge case with multiple streams with the same sampling rates but different responses has been skipped for now.
> add channel and component

- meta/citation.go
- meta/generate/main.go
- meta/list_test.go
- meta/set.go
- meta/set_auto.go
- meta/testdata/citations.csv
- references/README.md
- references/citations.csv
- tests/citations_test.go
- tests/consistency_test.go
This PR adds the code to read and write citation files.
I've added a "Pages" column mainly as it appears this is a source of an extra comma in the Volume which would then require quoting. To avoid this any page information will naturally flow with a comma following the Volume details.
> add citations code and add pages column

- install/README.md
- install/calibrations.csv
- internal/metadb/calibrations.go
- meta/calibration.go
- meta/list_test.go
- meta/testdata/calibrations.csv
- tests/calibrations_test.go
In line with other changes to channels and components, this PR updates the `calibration` table to use `Number` rather than `component`. The main reason for this is that a calibration can be added for a datalogger as well as a sensor, in which case a datalogger component has no real meaning.
> rename calibration component to number

- resp/auto.go
- resp/auto/sensor_Nanometrics-Inc_Trillium-Horizon-TH120-2.xml
- resp/responses/configurations/broadband.yaml
- resp/responses/sensors/nanometrics.yaml
This response is a replica of the original Nanometrics Trillium Horizon TH120-1. We are only adding it for naming clarity in delta so anyone out of the loop will realize the response is identical between both models (TH120-1 & TH120-2) and won't get into a panic thinking an unapproved sensor has been deployed from this point forwards.
If there is a better way to indicate and create awareness to people that the TH120-1 and TH120-2 are the same thing then I'm all ears and you can delete this PR.
More details as per linked ticket:
Model TH120-2
18437-02
ASM19106 rev. 10
> Nanometrics Trillium Horizon TH120-2 response added

- tests/stations_test.go
This is a shorter version of #1428 without the domains part. It simply updates the checks to allow duplicate stations, so long as the networks are different.
> all multiple stations with different networks

- install/README.md
- meta/testdata/polarities.csv
This is following on from instrument response work, and trying to avoid hidden logic in the instrument meta data generation.
This table is basically attempting to identify times when a recorded signal may be reversed from what is expected. How this information is gleaned is left as a reference where not straight forward.
I haven't added the full range of methods yet. I haven't decided whether to (a) build this into the code directly, or (b) create a table (perhaps in the references section) which can define methods of doing things. This can be extended to other tables or processes.
Just wanting feedback, on whether this covers the bases, whether there's something missing or otherwise. The code is there to implement this (as a proof of concept) but it doesn't need to be part of this …
> add polarity poc

- meta/generate/main.go
- meta/set.go
- meta/set_auto.go
This PR adds the new channel and component tables to the `Set` struct and updates the auto generated code to match.
> add channel and component to set

- meta/placenames.go
- meta/placenames_test.go
Just pulling this code into a more usable space, it also demonstrates and checks some of the `placename` function calls.
It's currently used for generating stationxml as a description note for stations and sites, relative to population centres.
> add description to PlacenameList and added a test

- meta/calibrations_test.go
- meta/channels_test.go
- meta/citations_test.go
- meta/components_test.go
- meta/gains_test.go
- meta/list_test.go
- meta/placenames_test.go
This is a general tidy up of the meta module testing mechanism, but so far only related to the recent updates associated with the stationxml revamp.
The main problem was the conflicts being generated in the `list_test.go` as new code is added or removed.  The changes simply add a function to replicate the existing tests (written prior to the t.Run mechanism) into a function which can be called on any given List.
This reduces changes to the main `list_test.go` file and separates each new table struct into individual files which should reduce the conflict potential.
There is no actual code "meta" code change here, just a reworking of the existing tests.
> update meta tests

- install/cameras.csv
Delta install/README.md says for cameras.csv 
Height | Installed camera vertical offset | metres positive upwards
-- | -- | --
But we had a mixture of positive and negative values, negative implying below the reference elevation which is normally the ground surface so below ground! Negative values come from a misunderstanding that the height in this file is the same as depth for seismic sensors, but it isn't.
All negative values replaced by the equivalent positive value.
> heights positive

- meta/polarity_test.go
- meta/testdata/polarities.csv
This PR adds in a base meta polarity test, based on #1502 it also updates the actual test data to match the new tests.
> update meta polarity tests

- install/README.md
- meta/component.go
- meta/testdata/components.csv
On final testing of calibrations updates a problem was found for sensors which can generate more than one type of output. An example would be the mass position of a broadband sensor, or the temperature of a fluxgate magnetometer.
The issue is that the stream is defined as Location, Band, Source, Sampling Rate, whereas the component is defined as Number, Subsource which means when joined together there will be too many streams.
The solution is to add a _Source_ field to the component so that the streams can be matched correctly.
> add source to component table

- tools/altus/altus_test.go
- tools/amplitude/amplitude_test.go
- tools/chart/chart_test.go
- tools/cusp/cusp_test.go
- tools/impact/impact_test.go
- tools/rinexml/site_test.go
- tools/spectra/spectra_test.go
- tools/stationxml/build_test.go
This is a bit of housework prior to go 1.19 update.
It replaces the original exec to diff checks with the use of the google cmp module.
> update tests to remove exec call, replace with cmp

- network/README.md
just noticed that this one was missing from the readme.
also, the README description of the "Method" column in network/views.csv is empty (https://github.com/GeoNet/delta/blob/main/network/README.md?plain=1#L116). And all values in the file are empty so not sure how to fill that in. Do you know what is that for?
> add to readme method column in network/sites

- internal/stationxml/response.go
- internal/stationxml/response_type.go
- internal/stationxml/root.go
- internal/stationxml/site.go
- resp/files/combined_Canterbury-Seismic-Instruments_Cusp_200sps.xml
- resp/files/combined_Canterbury-Seismic-Instruments_EQR120_200sps.xml
- resp/files/combined_GEM_Systems_GSM-19-1s.xml
- resp/files/combined_SAIC_BPR-Subsystem_BPR-Subsystem_Z_15s.xml
- resp/files/derived_Water-Depth-10s.xml
- resp/files/derived_Water-Depth-10sps.xml
- resp/files/derived_Water-Depth-1s.xml
- resp/files/derived_Water-Depth.xml
- resp/files/sensor_Danish_Meteorological_Institue_FGE.xml
- resp/files/sensor_Danish_Meteorological_Institue_FGE_Temperature.xml
- resp/resp_test.go
This PR adds the code to manipulate parts of a StationXML response type ,  it can join and normalise responses from different sensors and dataloggers.
It can adjust for different calibration values, gains, or preamps. 
It can also handle scaling of polynomial responses in a similar mannner.
This code only impacts the current system by adding a test in the `resp` directory to check that the generated or edited xml response files can read and decoded.
The next PRs will relate to encoding of this type into actual StationXML versions, as with the full StationXML root elements.
> add stationxml response decoding and snippet tests

- install/README.md
- install/telemetries.csv
- meta/correction.go
- meta/generate/generate.go
- meta/generate/main.go
- meta/meta.go
- meta/set.go
- meta/set_auto.go
- meta/telemetry.go
- meta/telemetry_test.go
- meta/testdata/telemetries.csv
- tests/telemetry_test.go
This PR tries to handle an edge case whereby the datalogger and the sensor are not at the same location and they are connected via analogue telemetry.  Either using FM radio or via leased-line modems.
This should add an extra stage in the response with notionally a gain of 1.0 (it's usually quite hard to work out the actual gain, but if this is done then the adjustment can be made here).
The main part is to add the `telemetries.csv` file and an extra related "Correction" option (very similar to the Preamp stage).
> Add a telemetry table

- resp/auto.go
- resp/responses/configurations/strongmotion.yaml
Missed one, this adds the BN? response details for the Cusp-Me devices.
> add 50Hz Cusp-Me resp

- internal/stationxml/decoder.go
- internal/stationxml/decoder10.go
- internal/stationxml/decoder11.go
- internal/stationxml/decoder12.go
This PR follows on from the encoder work.
Given a byte representation of an XML file, the decode will, depending on required version, extract the appropriate parts and return a cleaned byte slice. This code is primarily used to compare two different StationXML files and attempts to make the options uniform allowing comparisons.
> add stationxml decoder elements

- internal/stationxml/encoder.go
- internal/stationxml/encoder10.go
- internal/stationxml/encoder11.go
- internal/stationxml/encoder12.go
This PR introduces the code to encode specific stationxml versions, these will be fairly close, in fact v1.1 and v1.2 are the same from a code point of view (the difference is in documentation and formatting mainly).
The code basically does a mapping between the general stationxml elements (e.g. Station) and the version specific counterparts. It's a little confusing having two (or more) stationxml packages but this allows reading and writing specific versions of xml.
> add stationxml encode elements

- cmd/stationxml-compare/main.go
This application is used to verify that two StationXML files are the same within a set of encoding/decoding constraints. It's main use is to check update code returns the same values.
> add stationxml-compare

- tides/auto.go
Just catching up on old changes, this is a helper function for estimating what tidal heights should be via site codes. Just updating New Brighton and DART buoys.
> import updated constituents

- install/components.csv
Testing indicated that the site CBGS wasn't building stationxml files using the latest code, turns out the `Titan TACCL-N1` was missing an entry in the `components.csv` file.
> add Titan N1 to components list

- tests/antennas_test.go
- tests/assets_test.go
- tests/calibrations_test.go
- tests/cameras_test.go
- tests/combined_test.go
- tests/connections_test.go
- tests/consistency_test.go
- tests/constituents_test.go
- tests/dataloggers_test.go
- tests/doases_test.go
- tests/firmware_test.go
This is part of the delta test cleanup work with replacing individual calls to read files with using the built in `Set` features.
The may idea is to replace the standard test with a consistent function fingerprint, namely:
```golang
map[string]func(*meta.Set)func(t *testing.T)
```
Which allows building the set of tests via a map and a consistent calling mechanism, e.g.
``` golang
for k, v := range checks {
t.Run(k, v(set))
}
```
where checks is a map as defined above, and t a `testing.T` value.  Eventually the tests can be gathered and calling functions can be updated or adjusted as needed, e.g. to insert parallel running etc.
There are no changes to  the actual tests in this code, simply the framing.
> update delta testing to use set

- meta/collection.go
- tests/connections_test.go
This PR adds the ability to use the extra channels of an installed recorder to attach a sensor.
Requires the sensor channels, and components as per normal, but allows the option of using a connection with the Place being the recorder site, and the role the recorder location.
> feat(geomag): allow an recorder to use extra channels

- cmd/stationxml-build/build.go
- cmd/stationxml-build/main.go
This PR adds an option to suppress building the FIR filter delay/correction values (which are optional). Ideally they should be pointers and not encoded but that's a possible future step.
> feat(stationxml): adding filter delay/corrections off by default

- internal/stationxml/encoder10.go
A quirk of StationXML version 1.0 makes setting a stage gain tricky for polynomial responses, this update implements the previous mechanism. A better approach is used for stationxml 1.1 & 1.2.
> fix: add polynomial stage gain for version 1.0

- internal/stationxml/decoder10.go
- internal/stationxml/decoder11.go
- internal/stationxml/decoder12.go
- internal/stationxml/encoder10.go
- internal/stationxml/encoder11.go
- internal/stationxml/encoder12.go
- resp/generate/a2d.go
- resp/generate/fir.go
- resp/generate/paz.go
- resp/generate/polynomial.go
- resp/generate/stationxml.go
- tools/gloria/main.go
- tools/sit/main.go
For some reason the goimports command got confused with stationxml v1.? imports, needed to be hand fixed to match what was replaced
> fix: apply goimports to code base, manually fixed

- tools/sit/main.go
Doing a json encoding on protobufs isn't recommended. It fails to parse the linter checks due to an embedded mutex.
```
tools/sit/main.go:455:38: copylocks: call of json.MarshalIndent copies lock value: github.com/GeoNet/kit/sit_delta_pb.Site contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
out_json, _ := json.MarshalIndent(site_pb, "", "  ")
```
simple solution is to remove offending code as it was only used for debugging.
> fix: removed the tool/sit debug code which was breaking the linter

- resp/resp_test.go
Caused by the Parallel call, this then only checked the last response file.
The auto responses are generated using a different technique so will not match, unless the same mechanism is used. This will likely be fixed
> fix: bug with testing responses and do a double encode check

- cmd/stationxml-build/main.go
- internal/stationxml/encoder10.go
- internal/stationxml/encoder11.go
- internal/stationxml/encoder12.go
- internal/stationxml/root.go
This is an attempt to be more consistent with how the start/end dates for the networks are managed, previously each network was based on the times of the stations included. This worked except for when single station xml was being generated and each xml had a different network code based on the single station.  This method finds the times prior to building the xml, it also only uses stations which have had a sensor installed at some time in their past
> fix: update the way the stationxml networks get their start/end times

- cmd/stationxml-build/matcher.go
- cmd/stationxml-build/matcher_test.go
This will allow matching the current checks which use negative features (i.e. not these networks etc.)
> feat: extend matcher to negative checks

- cmd/stationxml-build/main.go
- internal/stationxml/root.go
This is used for building seiscomp3 config files in single mode, needed to match the existing output
> fix: update stationxml single file build parameters

- meta/collection.go
This is to allow for connections to recorders to ignore the built in sensor, previously these were being picked up and building extra channel elements.
> fix: with connections ignore streams for recorder installed sensors

- .github/workflows/build.yml
This swaps the testing actions to avoid overloaded testing debug, first check delta, then check the apps. This is to avoid confusing users with application code rather than delta file problems
> feat: update actions tests order

- cmd/bnc-config/build.go
- cmd/bnc-config/config.go
- cmd/bnc-config/config_test.go
- cmd/bnc-config/main.go
- cmd/ntripcaster-config/build.go
- cmd/ntripcaster-config/config.go
- cmd/ntripcaster-config/config_test.go
- cmd/ntripcaster-config/main.go
- internal/ntrip/ntrip.go
The config files may be split into two directories, common and otherwise. This adds the xtra requirements to find these files. It also updates the code into the settings structure.
> fix: required to split out common ntrip files

- test.sh
Hi Mark,
not sure if there's more to do for that, but this is to remove the now obsolete local test run for the deprecated `tools/stationxml`  folder
please let me know if there's more to do, or if wrong/unwanted we can just close this pr!
> chore: update local test to remove obsolete stuff

- cmd/stationxml-build/main.go
An error checking bug meant that files which were the same, other than their creation dates, were being treated as different, this removes that problem and also now checks for an output directory
> fix: correct the handling of single files

- meta/gauge.go
- meta/headers_test.go
- meta/list_test.go
- meta/mark.go
- meta/meta.go
- meta/metsensor.go
- meta/mount.go
- meta/sample.go
- meta/samples_test.go
- meta/site.go
- meta/station.go
This is to make way for the future table called point.  It's a straight s/Point/Position/g  s/point/position/g.
> chore: swap point with position

- go.mod
Reference: https://github.com/GeoNet/tickets/issues/13645
> chore: upgrade go version to 1.21

- meta/collection.go
- resp/files/combined_SAIC_BPR-Subsystem_BPR-Subsystem_Z_15s.xml
- resp/files/combined_SAIC_BPR-Subsystem_BPR-Subsystem_Z_900s.xml
The fake stage is needed for seiscomp to convert the fdsn xml.
Also fixes the multiple channels, due to the sampling rate being in the component aspect.
> fix: update dart response to include fake stage

- cmd/sensor-config/envirosensor.go
- cmd/sensor-config/gnss.go
- cmd/sensor-config/installed.go
- cmd/sensor-config/main.go
- cmd/sensor-config/manualcollect.go
- cmd/sensor-config/mount.go
- cmd/sensor-config/network.go
- cmd/sensor-config/settings.go
This XML format is a little easier to handle sensors that are installed at stations with unrelated network details, such as an acoustic sensor at a coastal gauge site, or a geomagnetic sensor at a strong motion site.
It removes the concept of the network (other than the total as a whole) and adds groups of sensors with a given characteristic. The type of installation is maintained, such as a Station/Sensor, or a Mark/Monument, or a Mount/View.
> feat: add grouped XML formatted sensor list

- tools/sitelogs/main.go
This update allows the sitelog code to check if there is a graph which includes a radome, if present, in which case that graph will be used. Otherwise, the antenna only graph will be used. In the configuration the antenna and radome should have a space between them.
> feat: add check for radome graph for sitelogs

- resp/info.go
- resp/instrument.go
- resp/resp.go
- resp/resp_test.go
- resp/response_type.go
This helps build configurations that simply needs sensitivities and gains etc.
Most of this code has been moved from internal/stationxml.
The main type InstrumentResponse is likely to be renamed once the current Response struct code is removed.
> feat: update the response code to build short response snippets

- meta/generate/generate.go
- meta/set_auto.go
This update removes the memory copies to improve the overall speed of operations, the original idea was to protect the underlying slice backends. But this approach is very slow with the memory allocation and handling, this update now returns the slices directly and is up to the module user to ensure integrity. The best approach is via using a range over the returned slice
On testing this change gives some programs a speed up of about x20.
> fix: update auto set code generation to improve application speed

- cmd/geomag-config/main.go
The resp module should now handle response file generation and encoding. This should be a noop change.
> chore: update geomag config to use resp

- cmd/chart-config/response.go
This updates the chart config app to use the resp module directly
> fix: update chart config to use resp

- cmd/stationxml-build/build.go
- internal/stationxml/encoder10.go
- internal/stationxml/encoder11.go
- internal/stationxml/encoder12.go
- internal/stationxml/root.go
- resp/response_type.go
The resp module should now handle response file generation and encoding. This should be a no-op change to how things run.
The Frequency() part is needed to expose the private frequency value (which is private to avoid it being encoded into the XML), this is only needed for version 1.0 and will be removed once we no longer need to maintain 1.0 (and 1.1).
> chore: replace response type in stationxml with resp module

- cmd/sensor-config/main.go
- cmd/sensor-config/mount.go
- cmd/sensor-config/settings.go
This makes the group name for cameras "Camera" rather than "Volcano Camera"
This option simply lists the camera networks,  an alternative would be to have a master "camera" network code and use this as the external camera code.  This could be addresses if we add more camera networks.
> fix: switch to use camera group

- cmd/tilde-config/coastal.go
- cmd/tilde-config/dart.go
- cmd/tilde-config/envirosensor.go
- cmd/tilde-config/geomag.go
This should handle the case of sites closing meaning the sensor is no longer installed rather than relying on the station times.
> fix: update tilde config to update site times instead of station times

- cmd/sc3-config/main.go
- cmd/sc3-config/station.go
This can happen if a temporary replacement site is installed without removing the existing one (which allows the second one to be promoted to being used).
> feat: add ability to skip seiscomp streams

- environment/README.md
- environment/visibility.csv
- meta/list_test.go
- meta/testdata/visibility.csv
- meta/visibility.go
This is part of making delta easier to reference via variables.
It is only used for GNSS sites and switching from Code to Mark makes it easier to track, other than the initial header swap there is no change to data or other applications.
> feat: update visibility table to use Mark label

- cmd/bnc-config/build.go
- cmd/bnc-config/config_test.go
- cmd/bnc-config/main.go
- cmd/bnc-config/skl.go
- cmd/bnc-config/skl_test.go
- cmd/bnc-config/testdata/AVLN-generic.SKL
- cmd/bnc-config/testdata/AVLN00NZL.SKL
- cmd/bnc-config/testdata/config.yaml
- cmd/bnc-config/testdata/install/antennas.csv
- cmd/bnc-config/testdata/install/firmware.csv
- cmd/bnc-config/testdata/install/radomes.csv
- cmd/bnc-config/testdata/install/receivers.csv
- cmd/bnc-config/testdata/network/monuments.csv
- go.mod
- go.sum
- vendor/github.com/GeoNet/Golang-Ellipsoid/LICENSE
- vendor/github.com/GeoNet/Golang-Ellipsoid/ellipsoid/ellipsoid.go
- vendor/modules.txt
- Added an optional switches for `bnc-config`
-  `-skl {path}` to generate Skeleton files, based on the configured sites. 
- `-summary {path-name}` to generate skeleton files summary so operators know how many files success/failed
- Also remove functionality to import aliases for bnc-config. ref https://github.com/GeoNet/tickets/issues/6495
Plan to run this from ac-tool, and generate SKL files into `puppet_gps_files/files/data/skl-{environment}` (or somewhere else, will decide in ac-tool). PR for ac-tool : https://github.com/GeoNet/ac-tools/pull/408
This is part of the steps towards https://github.com/GeoNet/tickets/issues/15788.
> feat: Skeleton file generating for bnc-config

- go.mod
This is needed to pass the vulnerability checks
> feat: bump go version to 1.22

- cmd/bnc-config/main.go
- cmd/bnc-config/skl.go
- cmd/bnc-config/skl_test.go
As title. Existing process is using NZL as SCTB's country code. Should be ATA instead, and the country code information is already in metadata (https://github.com/GeoNet/dmc-config/blob/main/config/gps-files/staging/mounts.csv).
This PR uses the country field in the metadata, instead of hard-coding NZL.
> fix: BNC-Client: SCTB skeleton file has incorrect country code

- install/components.csv
This should allow Duke sensors on the web site
> fix: switch "Short Period Borehole Seismometer" to "Short Period Seismometer"

- .github/CODEOWNERS
This extends the ownership of the golang parts to the platform/developer teams
> feat: extend CODEOWNERS file

- cmd/deltadb/README.md
- cmd/deltadb/main.go
- meta/sqlite/database.go
- meta/table.go
This is needed to extend initialisation of the deltadb to include other tables such as responses.
This rework shifts most of the database code away from the Table definitions, it now merely is a means of listing the various tables and their associated data.  This can then be used as needed by the actual database implementations.
This depends on #2275
> add transactions and a key value table for deltadb

- network/monuments.csv
- tests/consistency_test.go
This simply corrects a stray space at the end of a line in the monuments file. No expected changes other than that.
> feat: update consistency checks for monuments

- install/cameras.csv
- network/views.csv
This simply expands the time windows and adjusts a view code.  I notices WHOH was likely using the wrong view code based on the times.
> fix: adjust camera view and installation times

- cmd/tilde-config/gnss.go
Helps resolve https://github.com/GeoNet/tickets/issues/17322
Allows for station-level metadata fallback, whilst still maintaining the "no sensor" concept.
Responses now look like:
```json
"series": {
"domain": "gnss",
"station": "AVLN",
"name": "displacement",
"sensorCode": "nil",
"method": "1d",
"aspect": "up"
},
"latitude": -41.1964,
"longitude": 174.9329,
"elevationM": 40,
"datum": "WGS84",
"relativeHeightM": 0,
"valueUnit": "m",
"errorUnit": "m"
```
and
```json
"sensorCodes": {
"nil": {
"sensorCode": "nil",
"metadata": {
"latitude": -41.1964,
"longitude": 174.9329
},
```
> feat: add nil sensor to GNSS domain

- cmd/volcam-config/main.go
This updates the caption for the camera images, uses the view name to match the caption etc.
> fix: update the volcam config

- cmd/sensor-config/mount.go
This makes sure the camera install is within the view, which is within the mount
> fix: update sensor config

- tests/antennas_test.go
- tests/cameras_test.go
- tests/dataloggers_test.go
- tests/doases_test.go
- tests/metsensors_test.go
- tests/radomes_test.go
- tests/receivers_test.go
- tests/recorders_test.go
- tests/sensors_test.go
These checks help spot when something has been installed after it has been removed, or removed before it has been installed
> feat: add extra equipment installation checks

- resp/auto/sensor_Nanometrics-Inc_Trillium-Compact-20PH-2.xml
Due to the dual nature of naming things, there are multiple versions floating around of response files
The same as #2486 but different file.
> fix: updated second version

- cmd/volcam-config/main.go
Having two cameras with the same id will generate multiple update issues. This is a simple check to only process one, it relies on the order being correct as to which one it allows through.
> fix: avoid multiple volcam images per endpoint
