tests/marks_test.go
Treat GPS Antennas and Metsensors the same way as seimic sensors.
The is a sensor installed somewhere.  This may need further
breaking out into GPS vs GNSS capabilities (not sure yet if the antenna
affects this).  Remove marks.geojson creation.
=> GPS Antennas and MetSensors.

example/shake-config/main.go
Not to be merged into master, an example only.
=> add example shakenz config generator

helper/metadb/installation.go
Needed to check the installed sensor location, as well.
=> fixed installation bug

tools/chart/chart.go, tools/chart/chart_test.go, tools/chart/main.go, tools/chart/wave.go
@quiffman an update to chart to handle the wave-gauge config. This has a slightly different embedding than the other xml files, basically only plots and no pages. This needed a slight change to the Chart struct and the associated xml marshaling.
=> add wave gauge to chart

.travis.yml, build.sh
=> add build script

.travis.yml, build.sh, test.sh
Uses the terraform generated keys to sync `stationxml/complete.xml` to the `geonet-meta` bucket.
=> Plumb the stationxml and SEED generating parts in to the bucket.

.travis.yml
@quiffman travis part of Geonet/tickets#1522
=> add config env to travis

tools/impact/README.md, tools/impact/blessed.go, tools/impact/build.go, tools/impact/main.go
@quiffman just a bit of tidy up to make it a little more manageable, mainly with the blessed equipment being split out and a little more obvious.
=> updated impact to add readme

build.sh
This PR automates creating the Gloria protobufs and sends them to S3.
=> Send gloria protobuf to S3.

build.sh
@dc735 get them into s3 hopefully.
=> build rinexml files

install/metsensors.csv
Enacting resolution for GRAC from [this ticket](https://github.com/GeoNet/tickets/issues/1219#event-1244219039).
=> Remove metsensor metadata for GRAC.

resp/auto.go
@dc735 forgot the second part to #147
=> updated resp auto

tools/rinexml/main.go, tools/rinexml/status.go
@dc735 a first go at the operational, or not, rinex processing xml files. these can be adjusted to fit.
=> added rinexml on/off

tools/gloria/main.go
Updating the comments added to Gloria protobufs when they are generated.
=> Update Gloria Header Comment

build.sh, tools/stationxml/build.go, tools/stationxml/main.go
To help weed out the sc3 config file.
=> added "active" option

README.md, environment/README.md, install/README.md
@nbalfour @quiffman a first go at bringing the base README up to date and adding new ones in the environment and install directories.
This is still pretty much a skeleton with a few formatting inconsistencies still in there.
=> update and add readme files

install/README.md
@salichon good spotting. There are a few inconsistencies related to naming conventions which also need to updated at some point as well (e.g. Start/Stop vs Start Date, End Date etc).
=> Updated README for recorder fields.

network/monuments.csv
Hi Sam,
this is to update the monument height at TRAV, as measured yesterday.
Can you please review this pr?
Thanks!
=> update monument height at TRAV

network/monuments.csv
New data taken from photos:
AHTI,-1.5
BIRF,-1.37
BTHL,-1.58
HANA,-1.57
KAWK,-1.5
MAHA,-1.44
NMAI,-1.43
OKOH,-1.56
PARI,-1.54
SNST,-1.52
TRWH,-1.54
=> Update ground relationship data from photos.

tests/receivers_test.go
This looks like a copy/paste error that snuck through.
/cc @elidana
=> fixed receiver overlap test bug

tools/gloria/main.go
To fulfill https://github.com/GeoNet/gloria/issues/316
=> Third Party GNSS Sites List

tools/gloria/main.go
As described in https://github.com/GeoNet/gloria/issues/324
=> Fix radome span bug.

tools/sc3/autopick.go, tools/sc3/autopick_test.go, tools/sc3/global.go, tools/sc3/global_test.go, tools/sc3/main.go, tools/sc3/profile.go, tools/sc3/station.go, tools/sc3/station_test.go
Another initial go at an automatic template builder for sc3.
=> updated sc3 tool

tools/sc3/autopick.go, tools/sc3/global.go, tools/sc3/profile.go
Pulled the station key files down one step, and adjusted the global and autopick keys to stay in the same place (pushed the full path into the structs).
=> updated output file locations

go.mod, go.sum, tests/consistency_test.go, vendor/github.com/google/go-cmp/LICENSE, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/export_panic.go, vendor/github.com/google/go-cmp/cmp/export_unsafe.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go, vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go, vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go, vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go, vendor/github.com/google/go-cmp/cmp/internal/function/func.go, vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go, vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/internal/value/zero.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/report.go, vendor/github.com/google/go-cmp/cmp/report_compare.go, vendor/github.com/google/go-cmp/cmp/report_reflect.go, vendor/github.com/google/go-cmp/cmp/report_slices.go, vendor/github.com/google/go-cmp/cmp/report_text.go, vendor/github.com/google/go-cmp/cmp/report_value.go, vendor/modules.txt
@danieldooley can I get a review on this please.  It simply replaces a bit of hand rolled file diffing with and out of the box version from a google module as it's a lot more portable and fixes an issue with newer versions of travis.
=> updated test error checking for files

.travis.yml, run/after/ac-tools.sh
=> updated travis + ac-tools

.travis.yml
https://github.com/GeoNet/tickets/issues/6242
=> add slack notification on build failure

run/deploy/10-ac-tools-trigger.sh, run/deploy/10-sit-trigger.sh
@yanjunding updating the trigger scripts to now return a non-zero value when they fail.
=> update trigger scripts

run/deploy/10-sit-trigger.sh
And add the check to the sit script (which was after ac-tools).
=> update sit trigger script

network/monuments.csv
The monument height at NRSW has now been measured, this pr update its value.
=> add NRSW monument height

tests/antennas_test.go, tests/assets_test.go, tests/cameras_test.go, tests/combined_test.go, tests/connections_test.go, tests/consistency_test.go, tests/constituents_test.go, tests/dataloggers_test.go, tests/firmware_test.go, tests/gauges_test.go, tests/marks_test.go, tests/metsensors_test.go, tests/monuments_test.go, tests/networks_test.go, tests/radomes_test.go, tests/receivers_test.go, tests/recorders_test.go, tests/sensors_test.go, tests/sessions_test.go, tests/sites_test.go, tests/stations_test.go, tests/streams_test.go, tests/views_test.go
This is a reworking of the standard tests to be a little more consistent.
There's an update to the GNSS streams check, but apart from that it's all just moving code around.
The new layout is to have a table of functions that get called with sets of lists, these are then called in a loop by each test.
To see them in action, run `go test -v` in the `tests` directory (this will also show warnings).
=> updated delta tests

tools/impact/blessed.go
This should get a few more dots on the map.
=> add titan to the blessed list

meta/testdata/views.csv, meta/view.go, network/views.csv
This is just a cosmetic change to add the "Method" column to allow for specifying how the azimuth was calculated/estimated.
I've also swapped the order around to match the seismic site, i.e.  Azimuth, Method, Dip ....
=> add azimuth method

resp/auto.go, resp/responses/configurations/strongmotion.yaml, resp/responses/dataloggers/cusp.yaml, resp/responses/sensors/cusp.yaml
Team work on EQR120 New response 
integration of the recorder
=> Add EQR120 response 200HZ strong motion

network/monuments.csv
RLTN monument height has been now measured.
=> update monument height of RLTN GNSS site

tools/sitelogs/blank.go, tools/sitelogs/config/config.yaml, tools/sitelogs/config_auto.go, tools/sitelogs/main.go
Hi Mark,
my minor tweaks included here, hope that was the clean way you were looking for.
=> Sitelogs tweaks

run/deploy/10-ac-tools-trigger.sh, run/deploy/10-sit-trigger.sh
switching from master branch to main branch ...
=> now trigger main

tools/siteinfo/firmware.go
Hi @ozym ,
If you are happy with this can you please merge to your branch? I'd like to keep to comment to retrieve Gamit conversion file as well, just not sure if that is the right place in the go code
=> update firmware conversion list for Gamit stationinfo

tools/pod/blockette.go, tools/pod/pod.go
This may help with building dataless miniseed with newer sensors.
=> updated pod export for nanometrics sensors

network/networks.csv
Add EN network code for LRDCP sites.
=> add EN for lrdcp https://github.com/GeoNet/tickets/issues/7989

assets/dataloggers.csv
https://github.com/GeoNet/tickets/issues/8076
I need to update delta/assets/dataloggers.csv before I can update delta/install/dataloggers.csv
Added CR6 loggers.
=> lrdcp assets dataloggers.csv https://github.com/GeoNet/tickets/issues/8076

resp/auto.go, resp/responses/sensors/nanometrics.yaml
A small extra step that was missed when adding the horizon.
=> add horizon 120 to list of sensors

resp/auto.go, resp/responses/sensors/nanometrics.yaml
A section for the sensor description was missed out from previous response PR.
=> add sensor details for trillium borehole

resp/auto.go, resp/responses/configurations/pressure.yaml
Said one thing, did another. This is to update the dart sampling rate codes from VTZ, UTZ -> UTZ, WTZ.
=> update dart sample rate labels

network/README.md
This pull request add descriptions for some of the fields of the GNSS monument that were missing from the sensor network  README file.
/cc @ozym
=> add description for monument table in network README

assets/README.md, assets/doases.csv, install/README.md, install/doases.csv, tests/doases_test.go
This PR gets things ready for installing a scan doas equipment. It has empty files for assets and installs, plus tests based on the camera tests to make sure the data is internally consistent.
=> update simple docs and add empty doas files

tests/views_test.go
PR to allow for re-installation of cameras with a previous view.
=> update view test to allow for multiple installs

network/views.csv
Endtime for KAKA.02.
New line with startime for KAKA.01.
=> KAKA back to view code 01

network/views.csv
This is the revised view labels: Pretty much all camera view labels have been changed and made more consistent
=> Revised view labels

network/views.csv
This reverts commit 3e91b561992c30fbec174b24216008bf444c7bab.
It was more live than expected!
=> Revert "Revised view labels (#1153)"

tests/features_test.go
The reality of actual data, fixed a couple of bugs (!= vs ==) and variable overwrite.
=> update features tests

environment/features.csv, meta/feature.go, meta/list_test.go, meta/testdata/features.csv
This PR adds an "aspect" column to the features table. It's not in use yet so will have no impact on operational systems.
=> add feature aspect

environment/features.csv, tests/consistency_test.go
This adds the checks to make sure the feature files are the same on read as on write.
When we have more idea of how the system looks we can add more checks.
=> added features consistency test

tests/features_test.go
Hopefully this should handle multiple Locations but with different SubLocations.
=> update features test

.travis.yml, go.mod, vendor/modules.txt
As it says on the tin, just update travis for go1.16, the go.mod and any dependencies. No code has been changed.
=> update to go1.16

environment/README.md
I've noticed that some of the fields recently added in https://github.com/GeoNet/delta/pull/1224 where not described in the README.md file.
Trying here to add a description, happy to change anything that is not clearly stating what the new fields are capturing
=> Update environment readme file to add new fields in features.csv

environment/visibility.csv, tests/consistency_test.go
Turns out the visibility file wasn't being verified in testing.
Have added checks and updated the file to pass.
=> updated visibility checks

environment/visibility.csv
Added records about vegetation clearing at the AUCK site on 2021/03/24.
Is it looks fine and comply with our style of records?
=> Add info about AUCK site vegetation clearing

tests/features_test.go
Just adds an extra check to see if the property is different.
=> add features properties to overlap checks

install/streams.csv
Delta correction of a 1993 tmp deploy A11 short period station
=> A11 temp seismic station is EH not SH short period

install/polarities.csv, meta/generate/main.go, meta/polarity.go, meta/set.go, meta/set_auto.go, tests/polarities_test.go
This PR adds the code that goes with the polarities file poc #1426
Code outlines the file format, how to encode/decode it and updates the set base and auto generated parts.
The sets definition has also been updated to follow alphabetical listings to help with conflict management.
=> update polarity code

meta/station.go
Updating the sort mechanism for stations now that there's a chance a single station may have multiple networks.
=> update station sort order

meta/channel.go, meta/citation.go, meta/component.go, meta/constituent.go, meta/placenames.go
This PR cleans up some of the optional settings for the various decoding functions.  Mostly replaced by the existing ParseInt, ParseFloat code.
I've also updated the placename level to be optional, defaults to 0.
=> update optional values

meta/collection.go, meta/correction.go
This code joins the dataloggers, the sensors, and the streams for the times when they overlap.  There is also provision for times which may need adjustments (i.e. gains, polarities) which may not relate to the physical connections between the various parts.
This is the engine for building stationxml like meta data.
=> add collection code to set

install/channels.csv, install/components.csv, tests/resps_test.go
This is an initial commit to update the channel and component files.
I don't expect this to be the final version but simply a starting point and in some ways an illustration of how it will work.
I have also added a simple check to make sure the response file names exist as files to avoid typos as much as possible. This isn't used for anything currently, but is the major part of building future stationxml files.
=> update the response snippets and initial channel + component files

meta/collection.go
This PR catches up with the addition of the Correction application to Collection. The Correction code will discover the various options for ad hoc corrections, so that the Collection struct doesn't need to have these determined.
=> removed gain/calibration from Collection

internal/stationxml/response.go
This PR adds the newly merged telemetry code into the general response builder. It also adjusts the Preamp default value to better detect if one is being applied.
=> add telemetry stages

resp/auto.go, resp/responses/configurations/strongmotion.yaml, resp/responses/dataloggers/cusp.yaml, resp/responses/sensors/cusp.yaml
This PR adds the two CUSP building array datalogger/sensor combinations. It's assumed a CUSP-3C style response.
=> add CUSPM and CUSP-Me

docs/sheets/ENVIROSENSOR.md
starting some documentation for envirosensors. Still a draft
=> Envirosensors cheatsheet

cmd/stationxml-build/README.md, cmd/stationxml-build/build.go, cmd/stationxml-build/frequency.go, cmd/stationxml-build/main.go, cmd/stationxml-build/matcher.go
An initial program to build StationXML files of different versions.
=> add stationxml builder app

install/components.csv
For the new XML generation code, the component table needs to be updated. In this case the borehole titans.
=> update titan components

calibration/fluxgates/FGE_S0330.const.md, calibration/fluxgates/FGE_S0437-E0564.const.md, calibration/fluxgates/README.md
this is adding two additional calibration files. One of the two (S0437) also contains driver calibration
=> add calibration files of two fluxgates

cmd/stationxml-build/main.go
A small update to the stationxml builder application. This adds a flag "changed" which when set will only update the output stationxml file if the contents change other than the timestamp.
The stationxml schema requires a "Created" timestamp and is needed to pass the StationXML validators. However, as part of the CI/CD processes this file will be updated each time an update is run, with a new creation time but most likely otherwise the same contents.   This interferes with the processes used to detect changes in the network and adds extra processing and validation.
This PR allows a given output file to only be updated when the contents change, this is similar to how the single files are built as well.
=> add changed option to stationxml-build

cmd/stationxml-build/main.go, internal/stationxml/decoder10.go, internal/stationxml/decoder11.go, internal/stationxml/decoder12.go, internal/stationxml/encoder10.go, internal/stationxml/encoder11.go, internal/stationxml/encoder12.go, meta/channel.go, meta/component.go
This update adds in the Equipment fields for the stationxml encoding. It's using a Description method to generate the name (based on the Make, Model, and Type).
=> update stationxml configuring of equipment details

install/dataloggers.csv
Fixed site name capitalisation
=> fixed install/dataloggers.csv caves to Caves

tests/README.md, tests/consistency_test.go, tests/gains_test.go, tests/gauges_test.go, tests/marks_test.go, tests/metsensors_test.go, tests/monuments_test.go, tests/networks_test.go, tests/placenames_test.go, tests/radomes_test.go, tests/receivers_test.go, tests/recorders_test.go, tests/sensors_test.go, tests/sessions_test.go, tests/sites_test.go, tests/stations_test.go, tests/streams_test.go, tests/views_test.go
The final update to the test code, switch to a universal formatted call using the `*meta.Set` construct.
=> updated test files to use Set

network/networks.csv
Updating a couple of network spelling mistakes.
=> fix(spell): update network

.github/workflows/build.yml
Just removing the dispatch for now.
=> fix: update build workflow

cmd/stationxml-build/main.go
This is a no-op change, it simply moves the configuration into a struct
=> feat: switch to using a settings structure

cmd/stationxml-build/main.go
For building single files there are often extra criteria needed to decide which stations and channels to include based on start/end times.
=> feat: add operational checks

docs/sheets/ENVIROSENSOR.md
Basic editing of existing text.
Add a section on specific examples, with a subsection on replacing a datalogger
=> add new datalogger example

cmd/ndbc-update/deployment.go, cmd/ndbc-update/main.go, cmd/ndbc-update/template.go
The ndbc-update app is aimed at producing output suitable to send to noaa/ndbc via email or similar mechanism. It is still missing the sensor serial number
=> feat: add simple ndbc dart status app

cmd/camera-config/caption.go, cmd/camera-config/caption_test.go, cmd/camera-config/main.go, cmd/volcam-config/main.go, cmd/volcam-config/volcam.go, cmd/volcam-config/volcam_test.go
This updates the configuration of the volcam cameras from within delta
=> feat: add camera config apps

cmd/caps-config/main.go, cmd/caps-config/station.go, cmd/caps-config/station_test.go, cmd/sc3-config/autopick.go, cmd/sc3-config/autopick_test.go, cmd/sc3-config/global.go, cmd/sc3-config/global_test.go, cmd/sc3-config/main.go, cmd/sc3-config/profile.go, cmd/sc3-config/station.go, cmd/sc3-config/station_test.go
This produces the config for managing caps and sc3 systems
=> feat: add sc3 config apps

cmd/dart-config/config.go, cmd/dart-config/detide.go, cmd/dart-config/main.go, cmd/tilde-config/coastal.go, cmd/tilde-config/dart.go, cmd/tilde-config/envirosensor.go, cmd/tilde-config/main.go, cmd/tilde-config/manualcollect.go, cmd/tilde-config/testdata/tilde.xml, cmd/tilde-config/tilde.go, cmd/tilde-config/tilde_test.go
This includes configuration for tilde and dart processing configuration
=> feat: add extra apps

cmd/lrdcp-config/lrdcp.go, cmd/lrdcp-config/main.go
A revamp to use the Set base calls..
=> feat: add lrdcp config app

cmd/ndbc-update/main.go, cmd/ndbc-update/template.go
Pulling in some extra details into the format to handle the BPR sensor serial number.
=> fix: added serial number of bpr sensor to ndbc-update

install/channels.csv
add response file for JSCB, for 'historical' data
=> Add CUSP-M4 for JSCB

cmd/chart-config/README.md, cmd/chart-config/config.go, cmd/chart-config/config_test.go, cmd/chart-config/main.go, cmd/chart-config/response.go, cmd/chart-config/testdata/config.json
This application will be replacing the existing amplitude and spectral chart configuration tools as part of a reworking of the chart plotting mechanisms
=> feat: add chart config application

cmd/sensor-config/dart.go, cmd/sensor-config/envirosensor.go, cmd/sensor-config/gnss.go, cmd/sensor-config/installed.go, cmd/sensor-config/main.go, cmd/sensor-config/manualcollect.go, cmd/sensor-config/mount.go, cmd/sensor-config/network.go, cmd/sensor-config/network_test.go, cmd/sensor-config/testdata/sensor.xml
This makes a single output for installed sensors and related equipment
an example of the output can be found in `cmd/sensor-config/testdata/sensor.xml`
=> feat: add a sensor catalogue app

cmd/sensor-config/README.md, cmd/sensor-config/main.go, cmd/sensor-config/manualcollect.go, cmd/sensor-config/network.go, cmd/sensor-config/network_test.go, cmd/sensor-config/testdata/sensor.xml
This builds a sensor config file in either XML or json format. It documents the sensors and their locations as well as manually collection sites. This updates the JSON part.
=> feat: add sensor config

tools/siteinfo/main.go
This is related to building siteinfo logs which can't handle different intervals and therefore leave gaps
```
diff -u first second
--- first       2024-03-21 11:42:44.036435317 +1300
+++ second      2024-03-21 11:59:51.099085652 +1300
@@ -1,4 +1,4 @@
-*     GAMIT/GLOBK first
+*     GAMIT/GLOBK second
*
*     Generated by GeoNet on 2024-01-24 22:11 UTC
*     Send questions, comments or concerns to info@geonet.org.nz
@@ -261,7 +261,7 @@
CORM  Coromandel        2019 295 23 00 32  2020 105 22 20 27   0.0550  DHARP   0.0000   0.0000  TRIMBLE ALLOY         5.42                   5.42  5921R40137            TRM115000.00     NONE   1551016806
CORM  Coromandel        2020 105 22 20 28  2020 268 06 49 14   0.0550  DHARP   0.0000   0.0000  TRIMBLE ALLOY         5.43                   5.43 …
```
=> fix: handle sessions with different intervals

cmd/geomag-config/config.go, cmd/geomag-config/main.go, meta/correction.go
This adds a tool to generate geomag processing constants
=> feat: add geomag gain factor and bias config application

tests/features_test.go
This updates the features tests to look for mount/view options and to handle a sensor making multiple observation types, or aspects
=> chore: update features tests to handle scandoas

meta/feature.go
This should fix a problem with entering multiple features an different aspects.
=> chore: add extra features sorting code

install/components.csv, resp/files/sensor_Bartington_Mag670.xml
This adds the Bartington FGE sensor response.
Assumes 10,000 nT == 1 Volt (e.g 1 nT == 1/10000 Volts)
Frequency chosen as 1 Hz, not important unless full response is given.
Also response only applies to Z component.
=> chore: add Bartington response

cmd/geomag-config/main.go
This updates the geomag config application to handle sites with Bartington sensors that are not part of the main geomag network stations (e.g. SMHS).
=> feat: add Bartington response details to geomag config

cmd/tilde-config/main.go, cmd/tilde-config/scandoas.go
Reference: https://github.com/GeoNet/tickets/issues/15607
=> scandoas into Tilde

cmd/sensor-config/envirosensor.go, cmd/sensor-config/gnss.go, cmd/sensor-config/installed.go, cmd/sensor-config/manualcollect.go, cmd/sensor-config/mount.go, cmd/sensor-config/network.go
This updates the sensor config app to include network details and a feature label change
=> chore: update sensor config

cmd/sensor-config/envirosensor.go, cmd/sensor-config/gnss.go, cmd/sensor-config/installed.go, cmd/sensor-config/mount.go
This adds the sensor type to the sensor struct, usually this will match the group name.
=> chore: update sensor xml to add types at the sensor level

cmd/chart-config/config.go, cmd/chart-config/main.go
Fix a couple of minor typos
This is based on #1990 which got left in merge purgatory
=> bug: update spelling

test.sh
This should handle the updates to the config applications
=> fix: update the test script

resp/nrl/sensor_Streckeisen_STS-5A_LP120_SG1500_STgroundVel.xml, resp/resp.go, resp/resp_test.go
These can be used in the same way as the existing files in components or channels
=> feat: add a NRL directory to add externally derived response XML snippets

internal/stationxml/encoder10.go, internal/stationxml/encoder11.go, internal/stationxml/encoder12.go
This is to avoid having to decide whether to start from one or zero, each has its problems
=> feat: update polynomial coefficents to no longer be numbered

cmd/volcam-config/main.go
This is related to changing the camera labels which are used for file names as well as captions
=> fix: update volcam id names

cmd/sensor-config/envirosensor.go, cmd/sensor-config/gnss.go, cmd/sensor-config/installed.go, cmd/sensor-config/mount.go, cmd/sensor-config/network.go, cmd/sensor-config/network_test.go, cmd/sensor-config/testdata/sensor.xml
This should allow the sensor file to be used for serial name lookups
=> feat: add serial to the sensor xml

network/networks.csv
Add a sub-code for a network of GNSS at tide gauge stations, following the Delta meeting suggestion:  https://github.com/GeoNet/tickets/issues/16072#issuecomment-2316234259 and https://github.com/GeoNet/tickets/issues/16072#issuecomment-2316536023
=> GNSS@TG sub-network code

resp/files/sensor_Streckeisen_STS-6A.xml
This switches from a full response sensitivity to a sensor sensitivity
=> fix: update STS-6A response

cmd/sensor-config/main.go
This adds the SNZO non-standard settings to the sensor config code
=> feat: add SNZO to sensor config

cmd/bnc-config/skl.go, cmd/bnc-config/testdata/AVLN-generic.SKL, cmd/bnc-config/testdata/AVLN00NZL.SKL
This PR updates the skeleton file's template, as requested in the comments (and after) https://github.com/GeoNet/tickets/issues/16700#issuecomment-2359644163
=> feat: update BNC skeleton file formatter

cmd/bnc-config/skl.go, cmd/bnc-config/testdata/AVLN-generic.SKL
As title. 
As requestd by product owner.
=> feat: bnc skeleton file - marker name required in generic header

cmd/rsamtrig-config/config.go, cmd/rsamtrig-config/config_test.go, cmd/rsamtrig-config/global.go, cmd/rsamtrig-config/global_test.go, cmd/rsamtrig-config/main.go, cmd/rsamtrig-config/profile.go, cmd/rsamtrig-config/rsamtrig.go, cmd/rsamtrig-config/rsamtrig_test.go, cmd/rsamtrig-config/station.go, cmd/rsamtrig-config/station_test.go
This application is aimed at building and maintaining the sc configuration for the rsamtrig application
=> feat: add rsamtrig-config app

resp/resp.go
This is a set of helper functions to allow listing of the response file snippets available
=> feat: add ability to list response files

network/views.csv
Fix a simple typo in camera azimuth. Said 190 deg, should be 19 deg.
=> fix incorrect WHOH azimuth

cmd/coastal-config/README.md, cmd/coastal-config/config.go, cmd/coastal-config/detide.go, cmd/coastal-config/main.go
This adds a simple application to output a json configuration file which is suitable for coastal gauge processing, much like that generated for dart processing
=> feat: add coastal-config app

environment/notes.csv
The WGTT entry had an incorrect network code
=> fix: update notes network

cmd/sensor-config/main.go
This was missed in the original configuration
=> feat: add GT network to sensor config

tests/cameras_test.go
The test now check that there is a view open for the given camera install times
=> fix: update camera install test
